const data = [
    { name: "宋凯", school: "浙江大学", city: "杭州市", province: "浙江" },
    { name: "李科霖", school: "浙江大学", city: "杭州市", province: "浙江" },
    { name: "马超凡", school: "吉林大学", city: "长春市", province: "吉林" },
    { name: "赵倩", school: "天津理工大学", city: "西青区", province: "天津" },
    { name: "徐凯", school: "南开大学", city: "南开区", province: "天津" },
    { name: "刘嵘", school: "西南交通大学", city: "成都市", province: "四川" },
    { name: "韩杨", school: "四川大学", city: "成都市", province: "四川" },
    { name: "王奕博", school: "上海交大", city: "闵行区", province: "上海" },
    { name: "郭梓煜", school: "上海师范大学", city: "徐汇区", province: "上海" },
    { name: "王菲", school: "空军军医大学", city: "西安市", province: "陕西" },
    { name: "张笑寒", school: "青岛大学", city: "青岛市", province: "山东" },
    { name: "闫秋雯", school: "山东大学", city: "济南市", province: "山东" },
    { name: "王晓敏", school: "山东大学威海分校", city: "威海市", province: "山东" },
    { name: "孙思宇", school: "青岛大学", city: "青岛市", province: "山东" },
    { name: "宫国惠", school: "山东财经", city: "济南市", province: "山东" },
    { name: "逄雅茹", school: "南京农业大学", city: "南京市", province: "江苏" },
    { name: "郑爽", school: "南京航空航天大学", city: "南京市", province: "江苏" },
    { name: "逄博", school: "武汉大学", city: "武汉市", province: "湖北" },
    { name: "孙华彬", school: "哈尔滨工业大学", city: "哈尔滨市", province: "黑龙江" },
    { name: "于旻芮", school: "中山大学", city: "广州市", province: "广东" },
    { name: "胡凯", school: "中央民族大学", city: "海淀区", province: "北京" },
    { name: "张鹏杰", school: "北京理工大学", city: "海淀区", province: "北京" },
    { name: "殷强龙", school: "北京交通大学", city: "海淀区", province: "北京" },
    { name: "邬桐", school: "中国地质大学（北京）", city: "海淀区", province: "北京" },
    { name: "王牵", school: "中国农业大学", city: "海淀区", province: "北京" },
    { name: "刘金", school: "北京中医药大学", city: "海淀区", province: "北京" },
    { name: "李文超", school: "中国地质大学", city: "海淀区", province: "北京" },
    { name: "李厚霖", school: "中国人民大学", city: "海淀区", province: "北京" },
    { name: "李芳馨", school: "北京体育大学", city: "海淀区", province: "北京" },
    { name: "鞠宗宪", school: "对外经济贸易大学", city: "海淀区", province: "北京" },
    { name: "惠一丹", school: "中央财经大学", city: "海淀区", province: "北京" },
    { name: "韩晓阳", school: "北京科技大学", city: "海淀区", province: "北京" },
    { name: "管延彧", school: "北京航空航天大学", city: "海淀区", province: "北京" },
    { name: "管方明", school: "北京理工大学", city: "海淀区", province: "北京" },
    { name: "崔嘉程", school: "北京科技大学", city: "海淀区", province: "北京" },

];